project:
  type: website

website:
  title: "Cush Analytics"
  favicon: logo.png
  
  navbar:
    logo: images/logo.png
    reader-mode: true
    # google analytics
    googleAnalytics: "ua-164226979-1"
    disqusShortname: "alierreng" 
    right:
      - text: "About Me"
        href: about.qmd
      - text: "Resume"
        href: "https://cushanalytics.com/resume.pdf/"
      - icon: github
        href: https://github.com/tongakuot/
      - icon: twitter
        href: https://twitter.com/tongakuot/
      - icon: linkedin
        href: https://linkedin.com/in/tongakuot/
      - icon: youtube
        href: https://www.youtube.com/channel/UCWmRRNbHLNtbb13Hi1ucsFA

  page-footer:
      left: 
        - text: "&copy; 2022 Cush Analytics. All rights reserved." 
          href: "https://cushanalytics.com"
        - text: "About Me"
          href: about.qmd
        - text: "Resume"
          href: "https://cushanalytics.com/resume.pdf/"
          
      right: 
       - icon: github
         href: https://github.com/tongakuot/
       - icon: twitter
         href: https://twitter.com/tongakuot/
       - icon: linkedin
         href: https://linkedin.com/in/tongakuot/
       - icon: youtube
         href: https://www.youtube.com/channel/UCWmRRNbHLNtbb13Hi1ucsFA
      
        
         
  #comments:
    # disqus short name
    #disqusShortname: "alierreng"
    #giscus:
      #repo: tongakuot/cushanalytics_comments
      
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css

editor: visual

